site_name: Конструктор домашней автоматизации и умной квартиры
theme: default
docs_dir: docs
pages:
- 'Сообщество': 'index.md'
- Развертывание:
  - 'Выбор контроллера': 'Реализация.md'
  - 'Установка': 'Установка.md'
  - 'Настройка': 'Настройка.md'
  - 'Доступ из Интернет': 'Работа через Интернет.md'
- Сценарии:
  - 'Автополив цветов': 'Автополив цветов.md'
  - 'Управление освещением': 'Управление освещением.md'
  - 'Метеостанция': 'Метеостанция.md'
- Прототипирование:
  - 'Элементная база': 'Элементная база.md'
  - 'Микроконтроллеры': 'Микроконтроллеры.md'
  - 'Выбор элементов': 'Выбор элементов.md'
  - 'Сенсор CC41-A': 'Сенсор CC41A.md'
  - 'Сенсор JDY-10': 'Сенсор JDY-10.md'
  - 'Реле JDY-08': 'Реле JDY-08.md'
  - 'Бинарный сенсор JDY-08': 'Бинарный сенсор JDY-08.md'
- Концепция:
  - 'Умный дом': 'Введение.md'
  - 'Обзор рынка': 'Обзор рынка.md'
  - 'Архитектура': 'Архитектура.md'
  - 'Инфраструктура': 'Инфраструктура.md'
