site_name: Cute Care
docs_dir: docs
pages:
    - 'Начало': 'index.md'
    - 'Умный дом': 'Введение.md'
    - 'Обзор рынка': 'Обзор рынка.md'
    - 'Архитектура': 'Архитектура.md'
    - 'Реализация': 'Реализация.md'
    - 'Установка': 'Установка.md'
    - 'Элементная база': 'Элементная база.md'
    - 'Сенсор CC41-A': 'Сенсор CC41A.md'
    - 'Реле JDY-08': 'Реле JDY-08.md'
