site_name: Конструктор домашней автоматизации и умной квартиры
docs_dir: docs
pages:
- 'Сообщество': 'index.md'
- Концепция:
  - 'Умный дом': 'Введение.md'
  - 'Обзор рынка': 'Обзор рынка.md'
  - 'Архитектура': 'Архитектура.md'
- Развертывание:
  - 'Выбор контроллера': 'Реализация.md'
  - 'Установка и настройка': 'Установка.md'
- Прототипирование:
  - 'Элементная база': 'Элементная база.md'
  - 'Сенсор CC41-A': 'Сенсор CC41A.md'
  - 'Реле JDY-08': 'Реле JDY-08.md'
  - 'Бинарный сенсор JDY-08': 'Бинарный сенсор JDY-08.md'
