site_name: Конструктор домашней автоматизации и умной квартиры
theme: default
docs_dir: docs
pages:
- 'Сообщество': 'index.md'
- Развертывание:
  - 'Выбор контроллера': 'Реализация.md'
  - 'Установка': 'Установка.md'
  - 'Настройка': 'Настройка.md'
  - 'Доступ из Интернет': 'Работа через Интернет.md'
- Сценарии:
  - 'Автополив цветов': 'Автополив цветов.md'
  - 'Умная розетка': 'Умная розетка.md'
  - 'Управление освещением': 'Управление освещением.md'
  - 'Подсветка': 'Умная подсветка.md'
  - 'Метеостанция': 'Метеостанция.md'
  - 'Радионяня': 'Радионяня.md'
  - 'Детектор движения': 'Детектор движения.md'
- Прототипирование:
  - 'Элементная база': 'Элементная база.md'
  - 'Микроконтроллеры': 'Микроконтроллеры.md'
  - 'Выбор элементов': 'Выбор элементов.md'
- Концепция:
  - 'Умный дом': 'Введение.md'
  - 'Обзор рынка': 'Обзор рынка.md'
  - 'Архитектура': 'Архитектура.md'
  - 'Инфраструктура': 'Инфраструктура.md'
